name: movie_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_progress_hud: ^2.0.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_phone_field: ^3.2.0
  loop_page_view: ^1.2.5
  persistent_bottom_nav_bar_v2: ^5.3.1
  readmore: ^3.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.0+3
  top_snackbar_flutter: ^3.1.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
    - assets/onboarding/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
