// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-oN1ZS3-imC6tplu5Lsbt4cDFTo_pKU',
    appId: '1:1067285567354:web:14a1b8936e3c22e25428c3',
    messagingSenderId: '1067285567354',
    projectId: 'movie-zone-56744',
    authDomain: 'movie-zone-56744.firebaseapp.com',
    storageBucket: 'movie-zone-56744.firebasestorage.app',
    measurementId: 'G-1QTGL2V72Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBukaNp2n6LxxbKKbcbMyixlYIOXPp-H0',
    appId: '1:1067285567354:android:eddc9a233be08ed95428c3',
    messagingSenderId: '1067285567354',
    projectId: 'movie-zone-56744',
    storageBucket: 'movie-zone-56744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmWgqUBi_zv_-vgUytnbEqW_zV1bhb3Q8',
    appId: '1:1067285567354:ios:cd0d56b4efdf1d055428c3',
    messagingSenderId: '1067285567354',
    projectId: 'movie-zone-56744',
    storageBucket: 'movie-zone-56744.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

}